[disqus]
  disable = true

[googleAnalytics]
  anonymizeIP = true
  disable = true
  respectDoNotTrack = true
  useSessionStorage = false

[instagram]
  disable = true
  simple = false

[twitter]
  disable = false
  enableDNT = true
  simple = false

[vimeo]
  disable = true
  simple = false

[youtube]
  disable = false
  privacyEnhanced = true
