name: Blog
subtitle: Thom Wiggers's blog
markdown: redcarpet
pygments: true
relative_permalinks: false

author:
  name: Thom Wiggers
  email: thom@thomwiggers.nl
  github: thomwiggers
  twitter: thomwiggers

foundation-dev-mode: false

# don't put these on the live site
exclude: ['bower.json', 'index.html.bak', 'Rakefile']

linked_pages:
  - 
    url: "/index.html"
    title: "Home"
  - 
    url: "/about.html"
    title: "About"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/robots.txt"
  include_posts:
    - "/index.html"

defaults:
  -
    scope: 
      path: ""
    values:
      author: "Thom Wiggers"

