name: Blog
subtitle: Thom Wiggers' blog
description: Thom Wiggers' blog
url: https://thomwiggers.nl
markdown: Pandoc
highlighter: pygments
timezone: Europe/Amsterdam
paginate: 5

author:
  name: Thom Wiggers
  email: thom@thomwiggers.nl
  github: thomwiggers
  twitter: thomwiggers

foundation-dev-mode: false

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - bibliography: _tex/bibliography.bib
    - csl: _tex/lncs.csl

# don't put these on the live site
exclude:
  - bower.json
  - index.html.bak
  - Rakefile
  - README.md
  - config.rb
  - Gemfile
  - Gemfile.lock

# Explicitly include these
include: ['.well-known']

excerpt_separator: "<!-- more -->"

linked_pages:
  -
    url: "/index.html"
    title: "Home"
  -
    url: "/about.html"
    title: "About"
  -
    url: "/research/"
    title: "Research"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/robots.txt"
  include_posts:
    - "/index.html"


defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: "Thom Wiggers"
        url: "/about.html"

gems:
  - jekyll-pandoc
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

#  vim: set ts=4 sw=2 tw=80 et :
